# @package _global_
data_assimilation_steps: 50
model_integration_steps: 32
ensemble_size: 50
inflation_factor: 1.0
localization_distance: 10
spinup_steps: 25 # spinup run for spinup_steps * model_integration_steps


case:
  name: coupled_kuramoto
  title: "Coupled Kuramoto-Sivashinsky"
  num_states: 2
  state_dim: 1024
  obs_noise_variance: 0.1 # 0.09
  domain_length: 1024

  forward_model:
    _target_: non_gaussian_data_assim.forward_models.coupled_kuramoto_sivashinsky.CoupledKuramotoSivashinsky
    dt: 0.0625
    model_integration_steps: ${model_integration_steps}
    state_dim: ${case.state_dim}
    domain_length: ${case.domain_length}
    alpha_oa: 0.003
    omega_ao: 0.003
    lambda_a: 32.0
    lambda_o: 4.0
    tau_a: 1.0
    tau_o: 4.0

  obs_operator:
    _target_: non_gaussian_data_assim.observations.observation_operator.LinearObservationOperator
    state_dim: ${case.state_dim}
    num_states: ${case.num_states}
    obs_states: [0, 1]
    obs_indices:
      - _target_: numpy.arange
        start: 0
        stop: ${case.state_dim}
        step: 45
      - _target_: numpy.arange
        start: 0
        stop: ${case.state_dim}
        step: 15


  true_initial_state:
    _target_: non_gaussian_data_assim.initial_profiles.CoupledKuramotoPseudo1DProfile
    num_states: ${case.num_states}
    state_dim: ${case.state_dim}
    periodic: false
    scale: 1.0

    # CoupledKuramotoPseudo1DProfile --> Additionaly required
    domain_length: ${case.domain_length}
    decorrelation_length: 10.0


  initial_ensemble:
    _target_: non_gaussian_data_assim.ensemble_generation.initial_ensemble.InitialEnsemble
    centered_around_bestguess: false
    periodic: false

    ens_perturbation:

      # --- SmoothGaussianNoise
      _target_: non_gaussian_data_assim.ensemble_generation.ensemble_perturbations.CoupledKuramotoPseudo1DPerturbation
      num_states: ${case.num_states}
      state_dim: ${case.state_dim}
      domain_length: ${case.domain_length}
      decorrelation_length: 10.0
      scale: 1.0

      # # --- Breeding
      # _target_: non_gaussian_data_assim.ensemble_generation.ensemble_perturbations.BreedingPerturbation
      # num_states: ${case.num_states}
      # state_dim: ${case.state_dim}
      # forward_model: ${case.forward_model}
      # delta0: 5.0
      # breeding_cycles: 30
      # outer_steps_per_cycle: 32
      # norm_fct:
      #   _target_: non_gaussian_data_assim.ensemble_generation.breeding_vector.SelectedStateL2Norm
      #   state_index: 0  # 0:Fast Atmosphere.     ||       1: Slow ocean variable

      # # --- RedNoise ---
      # _target_: non_gaussian_data_assim.ensemble_generation.ensemble_perturbations.RedNoise
      # num_states: ${case.num_states}
      # state_dim: ${case.state_dim}
      # domain_length: ${case.domain_length}
      # scale: 1.0
      # alpha: 2.0

      # # --- WhiteNoise ---
      # _target_: non_gaussian_data_assim.ensemble_generation.ensemble_perturbations.WhiteNoise
      # num_states: ${case.num_states}
      # state_dim: ${case.state_dim}
      # scale: 10.0







  plotter:
    _target_: non_gaussian_data_assim.plotting.plot_fields.plot_multi_state_high_dim_field
    _partial_: true

  da_method_overrides:
    enkf:
      inflation_factor: ${inflation_factor}
      localization_distance: ${localization_distance}
    agmf:
      inflation_factor: ${inflation_factor}
      nc_threshold: 0.5
      localization_distance: ${localization_distance}
    pff:
      num_pseudo_time_steps: 100
      step_size: 1.0
      stepper: forward_euler
      localization_distance: ${localization_distance}
      inflation_factor: ${inflation_factor}
      prior_cov_regularization: 1.0e-2
    particle_filter:
      resample_threshold: 0.5
      jitter_scale: 0.05
