# @package _global_
data_assimilation_steps: 40
model_integration_steps: 10
ensemble_size: 50
inflation_factor: 1.0
localization_distance: 100
spinup_steps: 30 # spinup run for spinup_steps * model_integration_steps


case:
  name: kuramoto
  title: "Kuramoto-Sivashinsky"
  num_states: 1
  state_dim: 512
  obs_noise_variance: 0.1
  domain_length: 100

  forward_model:
    _target_: non_gaussian_data_assim.forward_models.kuramoto_sivashinsky.KuramotoSivashinsky
    dt: 0.05
    model_integration_steps: ${model_integration_steps}
    state_dim: ${case.state_dim}
    domain_length: ${case.domain_length}

  obs_operator:
    _target_: non_gaussian_data_assim.observations.observation_operator.LinearObservationOperator
    state_dim: ${case.state_dim}
    obs_states: [0]
    obs_indices:
      _target_: numpy.arange
      start: 0
      stop: ${case.state_dim}
      step: 4


  true_initial_state:
    _target_: non_gaussian_data_assim.initial_profiles.CosineProfile
    num_states: ${case.num_states}
    state_dim: ${case.state_dim}
    domain_length: ${case.domain_length}
    periodic: false
    magnitude: 1


  initial_ensemble:
    _target_: non_gaussian_data_assim.ensemble_generation.initial_ensemble.InitialEnsemble
    centered_around_bestguess: true
    periodic: ${case.true_initial_state.periodic}

    ens_perturbation:
      # --- SmoothGaussian / pseudo1D-like field perturbation ---
      # Recommended for KS if you want spatially structured initial uncertainty.
      _target_: non_gaussian_data_assim.ensemble_generation.ensemble_perturbations.CoupledKuramotoPseudo1DPerturbation
      num_states: ${case.num_states}
      state_dim: ${case.state_dim}
      domain_length: ${case.domain_length}
      decorrelation_length: 10.0
      scale: 1.0

      # # --- WhiteNoise ---
      # _target_: non_gaussian_data_assim.ensemble_generation.ensemble_perturbations.WhiteNoise
      # num_states: ${case.num_states}
      # state_dim: ${case.state_dim}
      # scale: 1.0

      # # --- RedNoise ---
      # _target_: non_gaussian_data_assim.ensemble_generation.ensemble_perturbations.RedNoise
      # num_states: ${case.num_states}
      # state_dim: ${case.state_dim}
      # scale: 1.0
      # alpha: 1.0

      # # --- Breeding ---
      # _target_: non_gaussian_data_assim.ensemble_generation.ensemble_perturbations.BreedingPerturbation
      # num_states: ${case.num_states}
      # state_dim: ${case.state_dim}
      # forward_model: ${case.forward_model}
      # delta0: 1.0
      # breeding_cycles: 10
      # outer_steps_per_cycle: 4


  plotter:
    _target_: non_gaussian_data_assim.plotting.plot_fields.plot_high_dim_field
    _partial_: true



  da_method_overrides:
    enkf:
      inflation_factor: ${inflation_factor}
      localization_distance: ${localization_distance}
      periodic: ${case.true_initial_state.periodic}
    agmf:
      inflation_factor: ${inflation_factor}
      nc_threshold: 0.5
      localization_distance: ${localization_distance}
      periodic: ${case.true_initial_state.periodic}
    pff:
      num_pseudo_time_steps: 10
      step_size: 0.1
      stepper: forward_euler
      localization_distance: ${localization_distance}
      inflation_factor: ${inflation_factor}
      prior_cov_regularization: 1.0e-2
      periodic: ${case.true_initial_state.periodic}
    particle_filter:
      resample_threshold: 0.5
      jitter_scale: 0.05
